#ifndef _simvascular_options_h
#define _simvascular_options_h
#define Qt5_MAJOR_VERSION 5
#define TCL_MAJOR_VERSION 8
#define PYTHON_MAJOR_VERSION 3 
#define FREETYPE_MAJOR_VERSION 2
#define MMG_MAJOR_VERSION 5
#define GDCM_MAJOR_VERSION 2
#define ITK_MAJOR_VERSION 4
#define OpenCASCADE_MAJOR_VERSION 7
#define MITK_MAJOR_VERSION 2018
#define Qt5_MINOR_VERSION 11
#define TCL_MINOR_VERSION 6
#define PYTHON_MINOR_VERSION 5 
#define FREETYPE_MINOR_VERSION 6
#define MMG_MINOR_VERSION 3
#define GDCM_MINOR_VERSION 6
#define ITK_MINOR_VERSION 13
#define OpenCASCADE_MINOR_VERSION 3
#define MITK_MINOR_VERSION 04
#define Qt5_PATCH_VERSION 3
#define TCL_PATCH_VERSION 4
#define PYTHON_PATCH_VERSION 5 
#define FREETYPE_PATCH_VERSION 3
#define MMG_PATCH_VERSION 9
#define GDCM_PATCH_VERSION 3
#define ITK_PATCH_VERSION 2
#define OpenCASCADE_PATCH_VERSION 0
#define MITK_PATCH_VERSION 2
#endif
