#ifndef SV4GUIMODULEIMAGEPROCESSING_EXPORT_H
#define SV4GUIMODULEIMAGEPROCESSING_EXPORT_H

#include "SimVascular.h"

#ifdef SV4GUIMODULEIMAGEPROCESSING_STATIC_DEFINE
#  define SV4GUIMODULEIMAGEPROCESSING_EXPORT
#  define SV4GUIMODULEIMAGEPROCESSING_NO_EXPORT
#else
#  ifndef SV4GUIMODULEIMAGEPROCESSING_EXPORT
#    ifdef sv4guiModuleImageProcessing_EXPORTS
       /* We are building this library */
#      define SV4GUIMODULEIMAGEPROCESSING_EXPORT SV_DLL_EXPORT
#    else
       /* We are using this library */
#      define SV4GUIMODULEIMAGEPROCESSING_EXPORT SV_DLL_IMPORT
#    endif
#  endif

#  ifndef SV4GUIMODULEIMAGEPROCESSING_NO_EXPORT
#    define SV4GUIMODULEIMAGEPROCESSING_NO_EXPORT
#  endif
#endif

#endif
