#ifndef SV4GUIMODULEPROJECTMANAGEMENT_EXPORT_H
#define SV4GUIMODULEPROJECTMANAGEMENT_EXPORT_H

#include "SimVascular.h"

#ifdef SV4GUIMODULEPROJECTMANAGEMENT_STATIC_DEFINE
#  define SV4GUIMODULEPROJECTMANAGEMENT_EXPORT
#  define SV4GUIMODULEPROJECTMANAGEMENT_NO_EXPORT
#else
#  ifndef SV4GUIMODULEPROJECTMANAGEMENT_EXPORT
#    ifdef sv4guiModuleProjectManagement_EXPORTS
       /* We are building this library */
#      define SV4GUIMODULEPROJECTMANAGEMENT_EXPORT SV_DLL_EXPORT
#    else
       /* We are using this library */
#      define SV4GUIMODULEPROJECTMANAGEMENT_EXPORT SV_DLL_IMPORT
#    endif
#  endif

#  ifndef SV4GUIMODULEPROJECTMANAGEMENT_NO_EXPORT
#    define SV4GUIMODULEPROJECTMANAGEMENT_NO_EXPORT
#  endif
#endif

#endif
